
# 00. PyTorch Fundamentals Exercises
## 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

    The documentation on torch.Tensor.
    The documentation on torch.cuda.



## 2: Create a random tensor with shape (7,7)

In [2]:
import torch

In [4]:
tensor = torch.rand(size = (7,7))
tensor

tensor([[0.8341, 0.8492, 0.8087, 0.3781, 0.2549, 0.0514, 0.0178],
        [0.4486, 0.1512, 0.4517, 0.8127, 0.9508, 0.8224, 0.8912],
        [0.4596, 0.0951, 0.6472, 0.7126, 0.8579, 0.0047, 0.5212],
        [0.5900, 0.0725, 0.4726, 0.8632, 0.0259, 0.2028, 0.9748],
        [0.6738, 0.7007, 0.8829, 0.1494, 0.5974, 0.3225, 0.5590],
        [0.3945, 0.9208, 0.5329, 0.6233, 0.9266, 0.9070, 0.9428],
        [0.2502, 0.6802, 0.3622, 0.7875, 0.5660, 0.8769, 0.9390]])

## 3: Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [11]:
tensor2 = torch.rand(1,7)
out1 = tensor2 @ tensor
out1, out1.shape

(tensor([[2.4793, 2.5383, 2.8876, 3.0205, 3.2306, 2.2604, 3.1020]]),
 torch.Size([1, 7]))

In [12]:
out2 = tensor @ tensor2.T
out2, out2.shape

(tensor([[2.4970],
         [2.8281],
         [2.0118],
         [2.1514],
         [3.0000],
         [3.5446],
         [2.9115]]),
 torch.Size([7, 1]))

## 4. Set the random seed to 0 and do 2 & 3 over again.

In [17]:
torch.manual_seed(seed = 0)

tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)
out  = tensor1 @ tensor2.T
out

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [21]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [22]:
tensor = tensor.to(device)

In [23]:
tensor.device

device(type='cpu')

In [25]:
torch.cuda.manual_seed(seed = 0)
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)
out  = tensor1 @ tensor2.T
out

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

In [27]:
torch.cuda.manual_seed(seed = 0)
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)
out  = tensor1 @ tensor2.T
out

tensor([[2.0942],
        [1.7132],
        [1.8574],
        [1.8773],
        [2.0426],
        [2.1253],
        [1.6462]])

## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [29]:
torch.manual_seed(1234)
tensor1, tensor2 = torch.rand(2,3).to(device), torch.rand(2,3).to(device)
tensor1, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [32]:
print(f'shape1: {tensor1.shape}')
print(f'shape2: {tensor2.shape}')

output = tensor1 @ tensor2.T
output, output.device, output.shape

shape1: torch.Size([2, 3])
shape2: torch.Size([2, 3])


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 device(type='cpu'),
 torch.Size([2, 2]))

## 8. Find the maximum and minimum values of the output of 7.

In [36]:
max = output.max()
min = output.min()
print(output)
print(f'Max: {max}')
print(f'Min: {min}')

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
Max: 0.5617256760597229
Min: 0.3647301495075226


## 9. Find the maximum and minimum index values of the output of 7.

In [44]:
argmax = torch.argmax(output, dim = 0)
argmin = torch.argmin(output, dim = 0)
print(output)
print(f'Argmin : {argmin}')
print(f'Argmax : {argmax}')

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
Argmin : tensor([0, 0])
Argmax : tensor([1, 1])


## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [47]:
tensor1 = torch.rand(1,1,1,10)
tensor1_squeezed = tensor1.squeeze()
print(tensor1, tensor1.shape)
print(tensor1_squeezed, tensor1_squeezed.shape)



tensor([[[[0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757, 0.7842, 0.1525,
           0.6662, 0.3343]]]]) torch.Size([1, 1, 1, 10])
tensor([0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757, 0.7842, 0.1525, 0.6662,
        0.3343]) torch.Size([10])


## End