## Section 0 : Pytorch Fundamentals

In [154]:
import torch
torch.__version__

'2.6.0+cpu'

## Introduction to Tensors

Tensors are the fundamental building block of machine learning.
Their job is to represent data in a numerical way 

Consider an image where you can have trhee color channels (for RGB) and then each channel would have 224/255 x 224/255 pixel values. This data can be represented as a 3d Tensor of [3, 224, 224].

The first Tensor is a scalar

A sclar is a single number an in tensor-speak it's a zero dimension tensor:
    - Documentation is more important to read for more comprehensive understanding


In [155]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [156]:
scalar.ndim

0

In [157]:
print(scalar.shape) # an empty list

torch.Size([])


In [158]:
# Turing the torch Tensor to a Python integer
scalar.item()


7

A ``vector`` is a single dimension tensor but can contain many numbers

In [159]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [160]:
vector.ndim


1

In [161]:
vector.shape

torch.Size([2])

In [162]:
# Matrix
MATRIX = torch.tensor([
    [7, 8],
    [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [163]:
# Check number of dimensions

MATRIX.ndim

2

In [164]:
MATRIX.shape

torch.Size([2, 2])

In [165]:
# Tensor 
TENSOR = torch.tensor([[
    [1, 2, 3],
    [3, 6, 9],
    [2, 4, 5]
]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Tensors can represent almost anything as long as it can be represented as a number

In [166]:
# consider this data frame (can be represeented in excel)

import pandas as pd

sample_df = pd.DataFrame({
    'Day': [1, 2, 3],
    'Steak Sales': [3, 6, 9],
    'Almond butter Sales': [2, 4, 5]
})
sample_df.head()


Day  Steak Sales  Almond butter Sales
0    1            3                    2
1    2            6                    4
2    3            9                    5

In [167]:
sample_tensor = torch.tensor([sample_df.values])

In [168]:
sample_tensor

tensor([[[1, 3, 2],
         [2, 6, 4],
         [3, 9, 5]]])

In [169]:
sample_tensor.shape

torch.Size([1, 3, 3])

In [170]:
sample_tensor.ndim

3

Representations:

- Scalar is a single number with 0 dimension , represented with ``a``
- Vector is a number with a direction with 1 dimensions, represented with ``y``
- Matrix is a 2 dimensional array of numbers, represented often as ``Q``
- Tensor is an n-dimensional array of numbers, represented often as ``X``

In [171]:
# Random Tensors
random_tensor =torch.rand((3,4))
random_tensor, random_tensor.dtype

(tensor([[0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969],
         [0.8317, 0.1053, 0.2695, 0.3588]]),
 torch.float32)

In [172]:
# Create a Random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand((224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [173]:
# TEnsors of Zeros and Ones
zeros = torch.zeros((3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [174]:
ones = torch.ones((3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [175]:
# Creating a Range and Tensors like

# range of numbers
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten_deprecated

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start= 0, end = 10, step = 1)
zero_to_ten

/tmp/ipykernel_85677/53359104.py:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
# Creating a new tensor(of zero and ones) similar to another tensor

ten_zeros = torch.zeros_like(input = zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [177]:
ten_ones = torch.ones_like(input= zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [178]:
torch.cuda

<module 'torch.cuda' from '/home/codespace/.local/lib/python3.12/site-packages/torch/cuda/__init__.py'>

In [179]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [180]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [181]:
new_float = float_32_tensor + float_16_tensor
new_float, new_float.dtype # the 16 moves to the default which is 32

(tensor([ 6., 12., 18.]), torch.float32)

In [182]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8613, 0.0919, 0.3102, 0.9536],
        [0.6002, 0.0351, 0.6826, 0.3743],
        [0.5220, 0.1336, 0.9666, 0.9754]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors

In [183]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [184]:
# Multiple it by 10
tensor * 10

tensor([10, 20, 30])

In [185]:
tensor

tensor([1, 2, 3])

In [186]:
# Subtract and Reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [187]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [188]:
# BUilt-in Functions

torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [189]:
tensor

tensor([1, 2, 3])

In [190]:
# Element WIse Multiplication
print(tensor, '*', tensor)
print('Equals', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


## Matrix Multiplication (is all you need)
using ```torch.matmul()``` method

Two Rules:

- The inner dimensions must match.
- The resulting matrix has the shape of the outer dimensions


In [191]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [192]:
# Element-wise matrix multiplication 
tensor * tensor

tensor([1, 4, 9])

In [193]:
# matrix wise multiplication

torch.matmul(tensor, tensor) # inner product

tensor(14)

In [194]:
# Can also use the @ sybmol for matrix multiplication, though not recommendation
tensor @ tensor

tensor(14)

In [195]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
    value += tensor[i]* tensor[i]
value

CPU times: user 244 μs, sys: 0 ns, total: 244 μs
Wall time: 250 μs


tensor(14)

In [196]:
%%time
value = tensor @ tensor
value

CPU times: user 53 μs, sys: 10 μs, total: 63 μs
Wall time: 67.2 μs


tensor(14)

In [197]:
# Shape Errors
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [198]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [199]:
# Transpose (switch the dimesnions of a given tensor)
print(tensor_B.T)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [200]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [201]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Neural Networks
The ```torch.nn.Linear()``` module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

$$ y = x\cdot{A^T} + b $$

Where
- x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
- A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
    - Note: You might also often see W or another letter like X used to showcase the weights matrix.
- b is the bias term used to slightly offset the weights and inputs.
- y is the output (a manipulation of the input in the hopes to discover patterns in it).




In [202]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible
torch.manual_seed(42)
# This uses matrix multiplication
linear =torch.nn.Linear(in_features=2, # in_features matches inner dimension of input
                        out_features=5) # out_features describes outer value
x = tensor_A
print(f'Input: \n{x}')
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input: 
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.3290,  1.2658,  0.6529,  0.5820, -0.0732],
        [ 4.5841,  2.2336,  0.6284,  0.7241,  0.1360],
        [ 6.8391,  3.2014,  0.6039,  0.8661,  0.3452]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 5])


In [203]:
linear.weight, linear.bias

(Parameter containing:
 tensor([[ 0.5406,  0.5869],
         [-0.1657,  0.6496],
         [-0.1549,  0.1427],
         [-0.3443,  0.4153],
         [ 0.6233, -0.5188]], requires_grad=True),
 Parameter containing:
 tensor([0.6146, 0.1323, 0.5224, 0.0958, 0.3410], requires_grad=True))

In [204]:
linear.weight.shape, linear.bias.shape

(torch.Size([5, 2]), torch.Size([5]))

# Finding the min, max, mean, sum etc (aggregation)

In [205]:
# Create a Tensor
x = torch.arange(0, 100, 10) # vector Tensor
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [206]:
x.dtype

torch.int64

In [207]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [208]:
# Positional Min/Max

# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f'Tensor: {tensor}')

# Returns the index of min and max values
print(f'Index where max value occurs: { tensor.argmax()}')
print(f'Index where min value occurs: { tensor.argmin()}')

## Shuffle the tensor up so that we don't know where the max index is 
import numpy as np
np.random.shuffle(tensor)

# Returns the index of min and max values
print(f'Index where max value occurs: { tensor.argmax()}')
print(f'Index where min value occurs: { tensor.argmin()}')


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0
Index where max value occurs: 8
Index where min value occurs: 0


/tmp/ipykernel_85677/2565760950.py:13: UserWarning: you are shuffling a 'Tensor' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  np.random.shuffle(tensor)


In [209]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [210]:
# Create a float16 tensor
tensor_float16 = tensor.type(dtype=torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [211]:
# Create an int8 tensor
tensor_int8 = tensor.type(dtype = torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

```Note:```  Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g 32, 16, 8), the less precise a computer stores the value. And witha lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based NN often operate with 8-bit integers, smaller and faster to run but less accurate that their float32 counterparts. 

## Reshaping, stacking, squeezing and unsqueezing

| Method                         | One-line description                                                                                      |
|---------------------------------|----------------------------------------------------------------------------------------------------------|
| `torch.reshape(input, shape)`   | Reshapes input to shape (if compatible), can also use `torch.Tensor.reshape()`.                          |
| `Tensor.view(shape)`            | Returns a view of the original tensor in a different shape but shares the same data as the original tensor.|
| `torch.stack(tensors, dim=0)`   | Concatenates a sequence of tensors along a new dimension (`dim`), all tensors must be same size.          |
| `torch.squeeze(input)`          | Squeezes input to remove all the dimensions with value 1.                                                 |
| `torch.unsqueeze(input, dim)`   | Returns input with a dimension value of 1 added at `dim`.                                                 |
| `torch.permute(input, dims)`    | Returns a view of the original input with its dimensions permuted (rearranged) to `dims`.                 |

In [212]:
# Create a tensor 
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [213]:
# Now, let's add an extra dimesnion with torch.reshape

x_reshaped = x.reshape(shape=(1, 7))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [214]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [215]:
# Changing z changes x
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [216]:
# but what about the reshaped tensor, also changes

x_reshaped[:, 0] = 10
x_reshaped, x

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.]))

In [218]:
# Stack tensors on top of each other
x_stacked_0 = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked_0

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.]])

In [222]:
x_stacked_1 = torch.stack([x, x, x, x], dim=1)
x_stacked_1

tensor([[10., 10., 10., 10.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.]])

In [223]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.])
New shape: torch.Size([7])


In [224]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.])
Previous shape: torch.Size([7])

New tensor: tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]])
New shape: torch.Size([1, 7])


In [225]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [226]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [227]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [228]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [229]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [230]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [233]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [239]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [240]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [241]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [242]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In [243]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

# 
print(f'Tensor A: \n {random_tensor_A}\n')
print(f'TEnsor B: \n {random_tensor_B}\n')
print(f'Does Tensor A equal Tensor B? (anywhere)')
random_tensor_A == random_tensor_B

Tensor A: 
 tensor([[0.0992, 0.3078, 0.7786, 0.8016],
        [0.3649, 0.6286, 0.9663, 0.7687],
        [0.4566, 0.5745, 0.9200, 0.3230]])

TEnsor B: 
 tensor([[0.8613, 0.0919, 0.3102, 0.9536],
        [0.6002, 0.0351, 0.6826, 0.3743],
        [0.5220, 0.1336, 0.9666, 0.9754]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [244]:
# manual seeding of the randomizers
import torch
import random

##Set the Random Seed
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(size = (3, 4))

In [246]:
random_tensor_C

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [247]:
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(size = (3, 4))
print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running Tensors on GPUs (and making faster computations)

| Method                   | Difficulty to setup | Pros                                                                 | Cons                                                      | How to setup                        |
|--------------------------|--------------------|---------------------------------------------------------------------|-----------------------------------------------------------|-------------------------------------|
| Google Colab             | Easy               | Free to use, almost zero setup required, can share work with others as easy as a link | Doesn't save your data outputs, limited compute, subject to timeouts | Follow the Google Colab Guide       |
| Use your own             | Medium             | Run everything locally on your own machine                          | GPUs aren't free, require upfront cost                    | [PyTorch installation guide](https://pytorch.org/get-started/locally/) |
[PyTorch installation guide](https://pytorch.org/get-started/cloud/)Follow the PyTorch installation guidelines |

In [250]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [251]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

Note: In Pytorch, it's best practice to write device agnostic code. This means that the code will run on CPU (always available) or GPU (if available)

In [252]:
# Count number of devices
torch.cuda.device_count()

0

In [253]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False

In [254]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [255]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [256]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [257]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

array([1, 2, 3])

In [258]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [259]:
tensor_on_gpu

tensor([1, 2, 3])